import React, { Component } from 'react'
import { connect } from 'react-redux'
import { bindActionCreators } from 'redux'
import { Formik, Form, Field } from 'formik'
import { Link } from 'react-router-dom'
import ProductsHandler from '../components/ProductHandler'